services:
  database:
    image: postgres:17
    environment:
      POSTGRES_DB: news_db       # Эта строка создаст БД при первом запуске
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - postgres_data:/var/lib/postgresql/data 

  backend:
    build: .
    ports:
      - "5002:5002"
    environment:
      - DB_HOST=database
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=12345
      - DB_NAME=news_db  # Добавьте это
    depends_on:
      database:
        condition: service_healthy

volumes:
  postgres_data: